Feature/language
kodolinija/stardeus-translations pull request #160
Opened 2022-11-15 10:43 UTC by blarrkan

Updated translations for Swedish

2022-11-15 14:12 UTC, blarrkan commented
Have I made a mistake here. Should the branch from my fork be Feature/Swedish instead of Feature/Language?

2022-11-15 16:04 UTC, spajus requested changes

2022-11-15 16:04 UTC, spajus commented on Translations/Swedish.csv
> +Key,Translation,Version,Comment
While sorting the file you shifted the first line which is the header into line 4, please revert this part :)

2022-11-15 18:15 UTC, blarrkan commented on Translations/Swedish.csv
> +Key,Translation,Version,Comment
Big sorry, This should now be sorted correctly.

2022-11-16 13:51 UTC, spajus approved these changes

2022-11-16 13:51 UTC, merged

2022-11-16 13:51 UTC, spajus commented
Thank you!